// Mocks generated by Mockito 5.4.6 from annotations
// in school_rec/test/features/reviews/state/reviews_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:school_rec/features/reviews/data/review_dtos.dart' as _i2;
import 'package:school_rec/features/reviews/data/review_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeReview_0 extends _i1.SmartFake implements _i2.Review {
  _FakeReview_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRepository extends _i1.Mock implements _i3.ReviewRepository {
  @override
  _i4.Future<List<_i2.Review>> listForSchool(int? schoolId) =>
      (super.noSuchMethod(
        Invocation.method(
          #listForSchool,
          [schoolId],
        ),
        returnValue: _i4.Future<List<_i2.Review>>.value(<_i2.Review>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Review>>.value(<_i2.Review>[]),
      ) as _i4.Future<List<_i2.Review>>);

  @override
  _i4.Future<_i2.Review> create(
    int? schoolId,
    _i2.ReviewInput? input,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            schoolId,
            input,
          ],
        ),
        returnValue: _i4.Future<_i2.Review>.value(_FakeReview_0(
          this,
          Invocation.method(
            #create,
            [
              schoolId,
              input,
            ],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Review>.value(_FakeReview_0(
          this,
          Invocation.method(
            #create,
            [
              schoolId,
              input,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Review>);

  @override
  _i4.Future<_i2.Review> update(
    int? reviewId,
    _i2.ReviewInput? input,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            reviewId,
            input,
          ],
        ),
        returnValue: _i4.Future<_i2.Review>.value(_FakeReview_0(
          this,
          Invocation.method(
            #update,
            [
              reviewId,
              input,
            ],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Review>.value(_FakeReview_0(
          this,
          Invocation.method(
            #update,
            [
              reviewId,
              input,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Review>);

  @override
  _i4.Future<void> delete(int? reviewId) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [reviewId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
