// Mocks generated by Mockito 5.4.6 from annotations
// in school_rec/test/features/schools/state/schools_list_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:school_rec/features/schools/data/school_dtos.dart' as _i2;
import 'package:school_rec/features/schools/data/school_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSchoolsPage_0 extends _i1.SmartFake implements _i2.SchoolsPage {
  _FakeSchoolsPage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSchool_1 extends _i1.SmartFake implements _i2.School {
  _FakeSchool_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFacilityImage_2 extends _i1.SmartFake implements _i2.FacilityImage {
  _FakeFacilityImage_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SchoolRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSchoolRepository extends _i1.Mock implements _i3.SchoolRepository {
  @override
  _i4.Future<_i2.SchoolsPage> list(_i2.SchoolListFilters? filters) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [filters],
        ),
        returnValue: _i4.Future<_i2.SchoolsPage>.value(_FakeSchoolsPage_0(
          this,
          Invocation.method(
            #list,
            [filters],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.SchoolsPage>.value(_FakeSchoolsPage_0(
          this,
          Invocation.method(
            #list,
            [filters],
          ),
        )),
      ) as _i4.Future<_i2.SchoolsPage>);

  @override
  _i4.Future<void> sendRecommendationFeedback({
    required int? historyId,
    required String? result,
    required int? schoolId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRecommendationFeedback,
          [],
          {
            #historyId: historyId,
            #result: result,
            #schoolId: schoolId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.School> getById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i4.Future<_i2.School>.value(_FakeSchool_1(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.School>.value(_FakeSchool_1(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.School>);

  @override
  _i4.Future<
      ({
        Map<String, dynamic> criteria,
        int? historyId,
        List<_i2.Recommendation> items
      })> recommend({
    _i2.Curriculum? curriculum,
    num? maxFee,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recommend,
          [],
          {
            #curriculum: curriculum,
            #maxFee: maxFee,
          },
        ),
        returnValue: _i4.Future<
            ({
              Map<String, dynamic> criteria,
              int? historyId,
              List<_i2.Recommendation> items
            })>.value((
          criteria: <String, dynamic>{},
          historyId: null,
          items: <_i2.Recommendation>[]
        )),
        returnValueForMissingStub: _i4.Future<
            ({
              Map<String, dynamic> criteria,
              int? historyId,
              List<_i2.Recommendation> items
            })>.value((
          criteria: <String, dynamic>{},
          historyId: null,
          items: <_i2.Recommendation>[]
        )),
      ) as _i4.Future<
          ({
            Map<String, dynamic> criteria,
            int? historyId,
            List<_i2.Recommendation> items
          })>);

  @override
  _i4.Future<void> follow(int? schoolId) => (super.noSuchMethod(
        Invocation.method(
          #follow,
          [schoolId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> followWithInteraction({
    required int? schoolId,
    int? recommendationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #followWithInteraction,
          [],
          {
            #schoolId: schoolId,
            #recommendationId: recommendationId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unfollow(int? schoolId) => (super.noSuchMethod(
        Invocation.method(
          #unfollow,
          [schoolId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateInteractionResult({
    required int? recommendationId,
    required int? schoolId,
    required String? result,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateInteractionResult,
          [],
          {
            #recommendationId: recommendationId,
            #schoolId: schoolId,
            #result: result,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.FacilityImage> uploadFacilityImage({
    required int? schoolId,
    required String? filename,
    required _i5.Uint8List? bytes,
    String? contentType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFacilityImage,
          [],
          {
            #schoolId: schoolId,
            #filename: filename,
            #bytes: bytes,
            #contentType: contentType,
          },
        ),
        returnValue: _i4.Future<_i2.FacilityImage>.value(_FakeFacilityImage_2(
          this,
          Invocation.method(
            #uploadFacilityImage,
            [],
            {
              #schoolId: schoolId,
              #filename: filename,
              #bytes: bytes,
              #contentType: contentType,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.FacilityImage>.value(_FakeFacilityImage_2(
          this,
          Invocation.method(
            #uploadFacilityImage,
            [],
            {
              #schoolId: schoolId,
              #filename: filename,
              #bytes: bytes,
              #contentType: contentType,
            },
          ),
        )),
      ) as _i4.Future<_i2.FacilityImage>);

  @override
  _i4.Future<void> deleteFacilityImage({
    required int? schoolId,
    required int? imageId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFacilityImage,
          [],
          {
            #schoolId: schoolId,
            #imageId: imageId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Set<int>> myFollowedSchoolIds() => (super.noSuchMethod(
        Invocation.method(
          #myFollowedSchoolIds,
          [],
        ),
        returnValue: _i4.Future<Set<int>>.value(<int>{}),
        returnValueForMissingStub: _i4.Future<Set<int>>.value(<int>{}),
      ) as _i4.Future<Set<int>>);

  @override
  _i4.Future<_i2.School> create({
    required String? schoolName,
    required String? address,
    required String? contactEmail,
    String? contactPhone,
    required _i2.Curriculum? curriculum,
    _i2.SchoolLevel? schoolLevel,
    required num? tuitionFee,
    String? facilities,
    double? latitude,
    double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [],
          {
            #schoolName: schoolName,
            #address: address,
            #contactEmail: contactEmail,
            #contactPhone: contactPhone,
            #curriculum: curriculum,
            #schoolLevel: schoolLevel,
            #tuitionFee: tuitionFee,
            #facilities: facilities,
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue: _i4.Future<_i2.School>.value(_FakeSchool_1(
          this,
          Invocation.method(
            #create,
            [],
            {
              #schoolName: schoolName,
              #address: address,
              #contactEmail: contactEmail,
              #contactPhone: contactPhone,
              #curriculum: curriculum,
              #schoolLevel: schoolLevel,
              #tuitionFee: tuitionFee,
              #facilities: facilities,
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.School>.value(_FakeSchool_1(
          this,
          Invocation.method(
            #create,
            [],
            {
              #schoolName: schoolName,
              #address: address,
              #contactEmail: contactEmail,
              #contactPhone: contactPhone,
              #curriculum: curriculum,
              #schoolLevel: schoolLevel,
              #tuitionFee: tuitionFee,
              #facilities: facilities,
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i4.Future<_i2.School>);

  @override
  _i4.Future<_i2.School> update({
    required int? id,
    String? schoolName,
    String? address,
    String? contactEmail,
    String? contactPhone,
    _i2.Curriculum? curriculum,
    _i2.SchoolLevel? schoolLevel,
    num? tuitionFee,
    String? facilities,
    double? latitude,
    double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #id: id,
            #schoolName: schoolName,
            #address: address,
            #contactEmail: contactEmail,
            #contactPhone: contactPhone,
            #curriculum: curriculum,
            #schoolLevel: schoolLevel,
            #tuitionFee: tuitionFee,
            #facilities: facilities,
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue: _i4.Future<_i2.School>.value(_FakeSchool_1(
          this,
          Invocation.method(
            #update,
            [],
            {
              #id: id,
              #schoolName: schoolName,
              #address: address,
              #contactEmail: contactEmail,
              #contactPhone: contactPhone,
              #curriculum: curriculum,
              #schoolLevel: schoolLevel,
              #tuitionFee: tuitionFee,
              #facilities: facilities,
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.School>.value(_FakeSchool_1(
          this,
          Invocation.method(
            #update,
            [],
            {
              #id: id,
              #schoolName: schoolName,
              #address: address,
              #contactEmail: contactEmail,
              #contactPhone: contactPhone,
              #curriculum: curriculum,
              #schoolLevel: schoolLevel,
              #tuitionFee: tuitionFee,
              #facilities: facilities,
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i4.Future<_i2.School>);

  @override
  _i4.Future<_i2.SchoolsPage> myFollowedSchools({
    int? limit = 50,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #myFollowedSchools,
          [],
          {
            #limit: limit,
            #page: page,
          },
        ),
        returnValue: _i4.Future<_i2.SchoolsPage>.value(_FakeSchoolsPage_0(
          this,
          Invocation.method(
            #myFollowedSchools,
            [],
            {
              #limit: limit,
              #page: page,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.SchoolsPage>.value(_FakeSchoolsPage_0(
          this,
          Invocation.method(
            #myFollowedSchools,
            [],
            {
              #limit: limit,
              #page: page,
            },
          ),
        )),
      ) as _i4.Future<_i2.SchoolsPage>);

  @override
  _i4.Future<void> revokeVerification(int? schoolId) => (super.noSuchMethod(
        Invocation.method(
          #revokeVerification,
          [schoolId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<int, int>> getRatingDistribution(int? schoolId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRatingDistribution,
          [schoolId],
        ),
        returnValue: _i4.Future<Map<int, int>>.value(<int, int>{}),
        returnValueForMissingStub:
            _i4.Future<Map<int, int>>.value(<int, int>{}),
      ) as _i4.Future<Map<int, int>>);
}
