// Mocks generated by Mockito 5.4.6 from annotations
// in school_rec/test/features/announcements/state/announcements_feed_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:school_rec/features/announcements/data/announcement_dtos.dart'
    as _i2;
import 'package:school_rec/features/announcements/data/announcement_repository.dart'
    as _i3;
import 'package:school_rec/features/announcements/data/comment_dtos.dart'
    as _i6;
import 'package:school_rec/features/auth/data/auth_dtos.dart' as _i8;
import 'package:school_rec/features/auth/state/auth_controller.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAnnouncement_0 extends _i1.SmartFake implements _i2.Announcement {
  _FakeAnnouncement_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AnnouncementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnnouncementRepository extends _i1.Mock
    implements _i3.AnnouncementRepository {
  @override
  _i4.Future<
      ({
        List<_i2.Announcement> items,
        int page,
        int total,
        int totalPages
      })> list({
    int? page = 1,
    int? limit = 20,
    _i2.AnnouncementCategory? category,
    _i2.UrgencyLevel? urgencyLevel,
    int? schoolId,
    bool? followedOnly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #page: page,
            #limit: limit,
            #category: category,
            #urgencyLevel: urgencyLevel,
            #schoolId: schoolId,
            #followedOnly: followedOnly,
          },
        ),
        returnValue: _i4.Future<
                ({
                  List<_i2.Announcement> items,
                  int page,
                  int total,
                  int totalPages
                })>.value(
            (items: <_i2.Announcement>[], page: 0, total: 0, totalPages: 0)),
        returnValueForMissingStub: _i4.Future<
                ({
                  List<_i2.Announcement> items,
                  int page,
                  int total,
                  int totalPages
                })>.value(
            (items: <_i2.Announcement>[], page: 0, total: 0, totalPages: 0)),
      ) as _i4.Future<
          ({
            List<_i2.Announcement> items,
            int page,
            int total,
            int totalPages
          })>);

  @override
  _i4.Future<_i2.Announcement> createForSchool(_i2.AnnouncementInput? input) =>
      (super.noSuchMethod(
        Invocation.method(
          #createForSchool,
          [input],
        ),
        returnValue: _i4.Future<_i2.Announcement>.value(_FakeAnnouncement_0(
          this,
          Invocation.method(
            #createForSchool,
            [input],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Announcement>.value(_FakeAnnouncement_0(
          this,
          Invocation.method(
            #createForSchool,
            [input],
          ),
        )),
      ) as _i4.Future<_i2.Announcement>);

  @override
  _i4.Future<_i2.Announcement> createForMoe(_i2.AnnouncementInput? input) =>
      (super.noSuchMethod(
        Invocation.method(
          #createForMoe,
          [input],
        ),
        returnValue: _i4.Future<_i2.Announcement>.value(_FakeAnnouncement_0(
          this,
          Invocation.method(
            #createForMoe,
            [input],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Announcement>.value(_FakeAnnouncement_0(
          this,
          Invocation.method(
            #createForMoe,
            [input],
          ),
        )),
      ) as _i4.Future<_i2.Announcement>);

  @override
  _i4.Future<void> delete(int? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Announcement> getById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Announcement>.value(_FakeAnnouncement_0(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Announcement>.value(_FakeAnnouncement_0(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Announcement>);

  @override
  _i4.Future<_i2.Announcement> uploadImage({
    required int? id,
    required String? filename,
    required _i5.Uint8List? bytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadImage,
          [],
          {
            #id: id,
            #filename: filename,
            #bytes: bytes,
          },
        ),
        returnValue: _i4.Future<_i2.Announcement>.value(_FakeAnnouncement_0(
          this,
          Invocation.method(
            #uploadImage,
            [],
            {
              #id: id,
              #filename: filename,
              #bytes: bytes,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Announcement>.value(_FakeAnnouncement_0(
          this,
          Invocation.method(
            #uploadImage,
            [],
            {
              #id: id,
              #filename: filename,
              #bytes: bytes,
            },
          ),
        )),
      ) as _i4.Future<_i2.Announcement>);

  @override
  _i4.Future<void> deleteImage(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteImage,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Comment>> getAnnouncementComments(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnnouncementComments,
          [id],
        ),
        returnValue: _i4.Future<List<_i6.Comment>>.value(<_i6.Comment>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.Comment>>.value(<_i6.Comment>[]),
      ) as _i4.Future<List<_i6.Comment>>);

  @override
  _i4.Future<void> postAnnouncementComment(
    int? announcementId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postAnnouncementComment,
          [
            announcementId,
            content,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i7.AuthController {
  @override
  bool get initializing => (super.noSuchMethod(
        Invocation.getter(#initializing),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> login(
    String? identifier,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            identifier,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> register({
    required String? fullName,
    String? email,
    String? phone,
    required String? password,
    required _i8.UserRole? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #fullName: fullName,
            #email: email,
            #phone: phone,
            #password: password,
            #role: role,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfile({
    String? fullName,
    String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #fullName: fullName,
            #phone: phone,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deactivate() => (super.noSuchMethod(
        Invocation.method(
          #deactivate,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reactivate(
    String? identifier,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reactivate,
          [
            identifier,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
