// Mocks generated by Mockito 5.4.6 from annotations
// in school_rec/test/features/auth/state/auth_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:school_rec/core/api_client.dart' as _i7;
import 'package:school_rec/core/auth_storage.dart' as _i6;
import 'package:school_rec/features/auth/data/auth_dtos.dart' as _i2;
import 'package:school_rec/features/auth/data/auth_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginResult_0 extends _i1.SmartFake implements _i2.LoginResult {
  _FakeLoginResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppUser_1 extends _i1.SmartFake implements _i2.AppUser {
  _FakeAppUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_2 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  @override
  _i5.Future<void> register({
    required String? fullName,
    String? email,
    String? phone,
    required String? password,
    required _i2.UserRole? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #fullName: fullName,
            #email: email,
            #phone: phone,
            #password: password,
            #role: role,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.LoginResult> login(
    String? identifier,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            identifier,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.LoginResult>.value(_FakeLoginResult_0(
          this,
          Invocation.method(
            #login,
            [
              identifier,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.LoginResult>.value(_FakeLoginResult_0(
          this,
          Invocation.method(
            #login,
            [
              identifier,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.LoginResult>);

  @override
  _i5.Future<void> verifyEmail(String? token) => (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resendVerification(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resendVerification,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> forgotPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #token: token,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [],
          {
            #currentPassword: currentPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.AppUser> getMe() => (super.noSuchMethod(
        Invocation.method(
          #getMe,
          [],
        ),
        returnValue: _i5.Future<_i2.AppUser>.value(_FakeAppUser_1(
          this,
          Invocation.method(
            #getMe,
            [],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.AppUser>.value(_FakeAppUser_1(
          this,
          Invocation.method(
            #getMe,
            [],
          ),
        )),
      ) as _i5.Future<_i2.AppUser>);

  @override
  _i5.Future<_i2.AppUser> updateMe({
    String? fullName,
    String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMe,
          [],
          {
            #fullName: fullName,
            #phone: phone,
          },
        ),
        returnValue: _i5.Future<_i2.AppUser>.value(_FakeAppUser_1(
          this,
          Invocation.method(
            #updateMe,
            [],
            {
              #fullName: fullName,
              #phone: phone,
            },
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.AppUser>.value(_FakeAppUser_1(
          this,
          Invocation.method(
            #updateMe,
            [],
            {
              #fullName: fullName,
              #phone: phone,
            },
          ),
        )),
      ) as _i5.Future<_i2.AppUser>);

  @override
  _i5.Future<_i2.LoginResult> reactivate(
    String? identifier,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reactivate,
          [
            identifier,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.LoginResult>.value(_FakeLoginResult_0(
          this,
          Invocation.method(
            #reactivate,
            [
              identifier,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.LoginResult>.value(_FakeLoginResult_0(
          this,
          Invocation.method(
            #reactivate,
            [
              identifier,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.LoginResult>);

  @override
  _i5.Future<void> deactivateMe() => (super.noSuchMethod(
        Invocation.method(
          #deactivateMe,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStorage extends _i1.Mock implements _i6.AuthStorage {
  @override
  _i5.Future<String?> readToken() => (super.noSuchMethod(
        Invocation.method(
          #readToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> writeToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #writeToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i7.ApiClient {
  @override
  _i3.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_2(
          this,
          Invocation.getter(#dio),
        ),
        returnValueForMissingStub: _FakeDio_2(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i3.Dio);

  @override
  set onUnauthorized(void Function()? value) => super.noSuchMethod(
        Invocation.setter(
          #onUnauthorized,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.Response<dynamic>> post(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
          },
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
}
