// Mocks generated by Mockito 5.4.6 from annotations
// in school_rec/test/features/notifications/state/notifications_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:school_rec/features/auth/data/auth_dtos.dart' as _i6;
import 'package:school_rec/features/auth/state/auth_controller.dart' as _i5;
import 'package:school_rec/features/notifications/data/notification_dtos.dart'
    as _i4;
import 'package:school_rec/features/notifications/data/notification_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i2.NotificationRepository {
  @override
  _i3.Future<
      ({
        List<_i4.AppNotification> items,
        int page,
        int total,
        int totalPages
      })> list({
    int? page = 1,
    int? limit = 20,
    bool? unreadOnly = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #page: page,
            #limit: limit,
            #unreadOnly: unreadOnly,
          },
        ),
        returnValue: _i3.Future<
                ({
                  List<_i4.AppNotification> items,
                  int page,
                  int total,
                  int totalPages
                })>.value(
            (items: <_i4.AppNotification>[], page: 0, total: 0, totalPages: 0)),
        returnValueForMissingStub: _i3.Future<
                ({
                  List<_i4.AppNotification> items,
                  int page,
                  int total,
                  int totalPages
                })>.value(
            (items: <_i4.AppNotification>[], page: 0, total: 0, totalPages: 0)),
      ) as _i3.Future<
          ({
            List<_i4.AppNotification> items,
            int page,
            int total,
            int totalPages
          })>);

  @override
  _i3.Future<void> markRead(int? id) => (super.noSuchMethod(
        Invocation.method(
          #markRead,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [AuthController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthController extends _i1.Mock implements _i5.AuthController {
  @override
  bool get initializing => (super.noSuchMethod(
        Invocation.getter(#initializing),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<void> login(
    String? identifier,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            identifier,
            password,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> register({
    required String? fullName,
    String? email,
    String? phone,
    required String? password,
    required _i6.UserRole? role,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #fullName: fullName,
            #email: email,
            #phone: phone,
            #password: password,
            #role: role,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateProfile({
    String? fullName,
    String? phone,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #fullName: fullName,
            #phone: phone,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deactivate() => (super.noSuchMethod(
        Invocation.method(
          #deactivate,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reactivate(
    String? identifier,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reactivate,
          [
            identifier,
            password,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
