// Mocks generated by Mockito 5.4.6 from annotations
// in school_rec/test/features/forum/state/forum_list_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:school_rec/features/forum/data/forum_dtos.dart' as _i2;
import 'package:school_rec/features/forum/data/forum_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForumPost_0 extends _i1.SmartFake implements _i2.ForumPost {
  _FakeForumPost_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ForumRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockForumRepository extends _i1.Mock implements _i3.ForumRepository {
  @override
  _i4.Future<({List<_i2.ForumPost> items, int page, int total, int totalPages})>
      list({
    int? page = 1,
    int? limit = 20,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #list,
              [],
              {
                #page: page,
                #limit: limit,
              },
            ),
            returnValue: _i4.Future<
                    ({
                      List<_i2.ForumPost> items,
                      int page,
                      int total,
                      int totalPages
                    })>.value(
                (items: <_i2.ForumPost>[], page: 0, total: 0, totalPages: 0)),
            returnValueForMissingStub: _i4.Future<
                    ({
                      List<_i2.ForumPost> items,
                      int page,
                      int total,
                      int totalPages
                    })>.value(
                (items: <_i2.ForumPost>[], page: 0, total: 0, totalPages: 0)),
          ) as _i4.Future<
              ({
                List<_i2.ForumPost> items,
                int page,
                int total,
                int totalPages
              })>);

  @override
  _i4.Future<_i2.ForumPost> getById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i4.Future<_i2.ForumPost>.value(_FakeForumPost_0(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ForumPost>.value(_FakeForumPost_0(
          this,
          Invocation.method(
            #getById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.ForumPost>);

  @override
  _i4.Future<_i2.ForumPost> create(String? content) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [content],
        ),
        returnValue: _i4.Future<_i2.ForumPost>.value(_FakeForumPost_0(
          this,
          Invocation.method(
            #create,
            [content],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ForumPost>.value(_FakeForumPost_0(
          this,
          Invocation.method(
            #create,
            [content],
          ),
        )),
      ) as _i4.Future<_i2.ForumPost>);

  @override
  _i4.Future<_i2.ForumPost> reply(
    int? parentId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reply,
          [
            parentId,
            content,
          ],
        ),
        returnValue: _i4.Future<_i2.ForumPost>.value(_FakeForumPost_0(
          this,
          Invocation.method(
            #reply,
            [
              parentId,
              content,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ForumPost>.value(_FakeForumPost_0(
          this,
          Invocation.method(
            #reply,
            [
              parentId,
              content,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ForumPost>);

  @override
  _i4.Future<_i2.ForumPost> update(
    int? id,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            id,
            content,
          ],
        ),
        returnValue: _i4.Future<_i2.ForumPost>.value(_FakeForumPost_0(
          this,
          Invocation.method(
            #update,
            [
              id,
              content,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ForumPost>.value(_FakeForumPost_0(
          this,
          Invocation.method(
            #update,
            [
              id,
              content,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ForumPost>);

  @override
  _i4.Future<void> delete(int? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
