import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:school_rec/features/recommendations/state/recommendations_controller.dart';
import 'package:school_rec/features/schools/data/school_dtos.dart';
import 'package:school_rec/features/schools/data/school_repository.dart';

import 'recommendations_controller_test.mocks.dart';

@GenerateNiceMocks([MockSpec<SchoolRepository>()])
School _school(int id) => School(
      id: id,
      schoolName: 'School $id',
      address: 'Address',
      contactEmail: 'school$id@example.com',
      contactPhone: null,
      curriculum: Curriculum.local,
      tuitionFee: 1000,
      facilities: null,
      latitude: null,
      longitude: null,
      rating: null,
      reviewCount: null,
      verificationStatus: VerificationStatus.pending,
      schoolLevel: null,
      schoolType: null,
      passingRate: null,
      nationalExamScore: null,
      facilityImages: const [],
      followerCount: null,
      distanceKm: null,
    );

// MockSchoolRepository will be generated by mockito.

void main() {
  group('RecommendationsController', () {
    test('refreshes recommendations with criteria and history id', () async {
      // Arrange
      final repo = MockSchoolRepository();
      when(repo.recommend(
              curriculum: anyNamed('curriculum'), maxFee: anyNamed('maxFee')))
          .thenAnswer((_) async => (
                items: [
                  Recommendation(
                    school: _school(1),
                    score: 0.9,
                    breakdown: const {'fees': 0.5},
                  ),
                ],
                criteria: {
                  'curriculum': 'LOCAL',
                  'maxFee': 5000,
                },
                historyId: 7,
              ));
      final controller = RecommendationsController(repo);
      await untilCalled(repo.recommend(
          curriculum: anyNamed('curriculum'), maxFee: anyNamed('maxFee')));

      // Act
      await controller.refresh(curriculum: Curriculum.local, maxFee: 5000);

      // Assert
      expect(controller.state.items.single.school.id, 1);
      expect(controller.state.criteria['curriculum'], 'LOCAL');
      expect(controller.state.historyId, 7);
      expect(controller.state.loading, isFalse);
    });
  });
}
